### ISSUE TITLE
Create legal user is natural endpoint

### ISSUE THREAD

**Issue by xavxyz** [jalik/jalik-mangopay#1]
Hey @jalik! Thanks for building this package :+1: 

I'm using it on a client's project and I just noticed that the endpoint you use for the creation of legal user is the natural endpoint.
https://github.com/jalik/jalik-mangopay/blob/master/api/user.js#L42

I'm forking your package in order to fix this and of course to help you in this work in progress! :) I'll do my some modifications if I see any trouble with it. I'll do a PR later ! 

Cheers

**Comment by jalik** [comment]
@xavizalote thank you for spotting the bug and sorry for that. Do you want to propose a PR or do I fix it myself ?

**Comment by xavxyz** [comment]
Well, here it is: #2 :+1:
I've don't see any other trouble, the package works great!

**Comment by jalik** [comment]
Thx, I am gonna publish it now.
